[2022-10-03 20:52:45,469] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_star_wars.create_films_table manual__2022-10-03T20:52:42.654227+00:00 [queued]>
[2022-10-03 20:52:45,487] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_star_wars.create_films_table manual__2022-10-03T20:52:42.654227+00:00 [queued]>
[2022-10-03 20:52:45,488] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-03 20:52:45,488] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-10-03 20:52:45,495] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-03 20:52:45,512] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_films_table> on 2022-10-03 20:52:42.654227+00:00
[2022-10-03 20:52:45,520] {standard_task_runner.py:52} INFO - Started process 2332 to run task
[2022-10-03 20:52:45,526] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_star_wars', 'create_films_table', 'manual__2022-10-03T20:52:42.654227+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ingest_starwars_data.py', '--cfg-path', '/tmp/tmp2e7nxnfj', '--error-file', '/tmp/tmpw1pv96d9']
[2022-10-03 20:52:45,528] {standard_task_runner.py:77} INFO - Job 16: Subtask create_films_table
[2022-10-03 20:52:45,635] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_star_wars.create_films_table manual__2022-10-03T20:52:42.654227+00:00 [running]> on host 86c7e9112604
[2022-10-03 20:52:45,745] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=xxxx@xxxxx.com
AIRFLOW_CTX_DAG_OWNER=Ram
AIRFLOW_CTX_DAG_ID=ingest_star_wars
AIRFLOW_CTX_TASK_ID=create_films_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T20:52:42.654227+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-03T20:52:42.654227+00:00
[2022-10-03 20:52:45,759] {base.py:79} INFO - Using connection to: id: postgres_local. Host: host.docker.internal, Port: 5432, Schema: postgres, Login: postgres, Password: ***, extra: {}
[2022-10-03 20:52:45,820] {dbapi.py:225} INFO - Running statement: CREATE TABLE IF NOT EXISTS star_wars_films (
            title TEXT,
            episode_id TEXT,
            opening_crawl TEXT,
            director TEXT,
            producer TEXT,
            release_date TEXT,
            characters TEXT,
            planets TEXT,
            starships TEXT,
            vehicles TEXT,
            species TEXT,
            created TEXT,
            edited TEXT,
            url TEXT
            );, parameters: None
[2022-10-03 20:52:45,825] {postgres.py:71} INFO - NOTICE:  relation "star_wars_films" already exists, skipping

[2022-10-03 20:52:45,868] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_star_wars, task_id=create_films_table, execution_date=20221003T205242, start_date=20221003T205245, end_date=20221003T205245
[2022-10-03 20:52:45,911] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-10-03 20:52:45,951] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
