[2022-10-04 13:29:56,848] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_star_wars.trigger_star_wars_agg_dag scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-10-04 13:29:56,862] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_star_wars.trigger_star_wars_agg_dag scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2022-10-04 13:29:56,863] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 13:29:56,864] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-10-04 13:29:56,865] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 13:29:56,881] {taskinstance.py:1259} INFO - Executing <Task(TriggerDagRunOperator): trigger_star_wars_agg_dag> on 2022-10-03 00:00:00+00:00
[2022-10-04 13:29:56,897] {standard_task_runner.py:52} INFO - Started process 3894 to run task
[2022-10-04 13:29:56,909] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_star_wars', 'trigger_star_wars_agg_dag', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/ingest_starwars_data.py', '--cfg-path', '/tmp/tmptpikpdv2', '--error-file', '/tmp/tmpqgdanpkr']
[2022-10-04 13:29:56,916] {standard_task_runner.py:77} INFO - Job 43: Subtask trigger_star_wars_agg_dag
[2022-10-04 13:29:56,992] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_star_wars.trigger_star_wars_agg_dag scheduled__2022-10-03T00:00:00+00:00 [running]> on host be1a5b89e146
[2022-10-04 13:29:57,078] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=xxxx@xxxxx.com
AIRFLOW_CTX_DAG_OWNER=Ram
AIRFLOW_CTX_DAG_ID=ingest_star_wars
AIRFLOW_CTX_TASK_ID=trigger_star_wars_agg_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2022-10-04 13:29:57,125] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/api/common/experimental/trigger_dag.py:91: DeprecationWarning: Calling `DAG.create_dagrun()` without an explicit data interval is deprecated
  dag_hash=dag_bag.dags_hash.get(dag_id),

[2022-10-04 13:29:57,157] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_star_wars, task_id=trigger_star_wars_agg_dag, execution_date=20221003T000000, start_date=20221004T132956, end_date=20221004T132957
[2022-10-04 13:29:57,205] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-10-04 13:29:57,253] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
